name: 'Close stale issues and PRs'
on: workflow_call

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          exempt-all-milestones: true
          exempt-issue-labels: bug
          exempt-pr-labels: bug
          remove-stale-when-updated: true

          days-before-issue-close: 30
          days-before-issue-stale: 90
          stale-issue-label: stale
          stale-issue-message: |
            This issue is stale because it has been open 90 days with no activity.
            Remove stale label or comment or this will be closed in 30 days.
          close-issue-label: closed-by-stale
          close-issue-message: |
            This issue was closed because it has been stale for 30 days and there was
            no response after warning of closure.

          # stale prs are no longer closed
          days-before-pr-close: -1
          days-before-pr-stale: 7
          stale-pr-label: stale
          stale-pr-message: |
            This issue is stale because it has been open 180 days with no activity.
            Remove stale label or comment or this will be closed in 30 days.
          close-pr-label: closed-by-stale
          close-pr-message: |
            This issue was closed because it has been stale for 30 days and there was
            no response after warning of closure.
